### ISSUE TITLE
Dependabot not checking out private actions

### ISSUE THREAD

**Issue by logineimer** [daspn/private-actions-checkout#27]
Hi there! We use your neat little action for checking out private actions in our organization. However, workflows triggered by Dependabot aren't able to fetch the private actions. Here's some example error log we receive:

```
SSH > Cloning using SSH strategy
SSH > No private key provided. Assuming valid SSH credentials are available
SSH > git clone --depth=1 --single-branch --branch main git@github.com:organization/private-actions.git ./.github/actions/private-actions
Cloning into './.github/actions/private-actions'...
Error: Error: Command failed: git clone --depth=1 --single-branch --branch main git@github.com:organization/private-actions.git ./.github/actions/private-actions
Cloning into './.github/actions/private-actions'...
Warning: Permanently added the RSA host key for IP address '140.[8](https://github.com/organization/consuming-project/runs/5058799050?check_suite_focus=true#step:3:8)2.[11](https://github.com/organization/consuming-project/runs/5058799050?check_suite_focus=true#step:3:11)4.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

We use the action like that:

```
- uses: daspn/private-actions-checkout@v2
  with:
    actions_list: '["organization/private-actions@main"]'
    ssh_private_key: ${{ secrets.PRIVATE_ACTIONS_SSH_PRIVATE_KEY }}
```

The referenced SSH public key is set as a deploy key in the private actions repo while the private key lives in a organization wide secret (Actions and Dependabot).

Do you have any idea what's wrong here?

**Comment by daspn** [comment]
Hi @logineimer !

Did you double checked the secrets specific for the Dependabot?

![image](https://user-images.githubusercontent.com/3356649/152536190-d9559866-98b6-4771-946f-3add8856eae0.png)
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions

Looks like you're not getting the `PRIVATE_ACTIONS_SSH_PRIVATE_KEY` value correctly.

**Comment by daspn** [comment]
I just asked you to double check since as per the docs there's nothing wrong with your code or the action's code. Can you try to "print" the secret value (maybe print the len(SECRET_VALUE)) just to make just the Dependant bot is receiving it correctly?

**Comment by logineimer** [comment]
I'll try it and come back to you after that! :)

**Comment by daspn** [comment]
@logineimer do you have some news to share here?

**Comment by daspn** [comment]
I can't see why it's failing, since deploy keys are pretty much the same as user account keys (except they work only on a single repository). You can also check the value stored on `PRIVATE_ACTIONS_SSH_PRIVATE_KEY`, making sure the content is correctly preserved (formatting, new line characters and so on).
I usually use `pbcopy`(on a Mac) to grab the private key contents on a "safe" way:
`cat /path/to/my/private/key | pbcopy` (then just paste on the GitHub's UI)

**Comment by logineimer** [comment]
Hey @daspn! Thanks for your patience. I've been discovering that workflows triggered by Dependabot seem to work now. I'm not sure if the issue was caused by some GitHub backend stuff which wasn't properly synced or something else. Recent workflows cause no trouble. I'd see this issue resolved. :)
