### ISSUE TITLE
Deprecation warnings (node, set-output, save-state)

### ISSUE THREAD

**Issue by davemaul** [daspn/private-actions-checkout#37]
Hello there,

we are happily using your action to work around non enterprise restrictions on private actions. The action seems to use Node.js 12 at the moment which is deprecated by GitHub: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

This leads to warning outputs in job summaries.

Furthermore, the actions seems to use `set-output` and `save-state` commands under the hood which i believe comes from an old version of `@actions/core` or smth else. This is deprecated too: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Should update to `@actions/core@1.10.0`.

Best regards!

**Comment by davemaul** [comment]
Oh btw: The actions seems to use `set-output` and `save-state` commands under the hood which i believe comes from an old version of `@actions/core` or smth else. This is deprecated too: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by gthomson31** [comment]
Is there any news on if this will be patched ?

**Comment by herebebeasties** [comment]
I've added #39 which patches this, which is passing all the tests.

**Comment by daspn** [comment]
@davemaul thanks to the contribution from @herebebeasties the action is now using Node.js 16. The latest version also includes patches to all Dependabot recent alerts. Thank you guys for keeping this project up to date.

**Comment by davemaul** [comment]
Thanks a lot!

**Comment by gthomson31** [comment]
thanks! :D
